[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = """        RENTAL = HEX('b18f43'),"""
position = "after"
payload = """SP_SHUFFYORANGE = HEX("e67e22"),"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """  return G.ARGS.LOC_COLOURS[_c] or _default or G.C.UI.TEXT_DARK"""
position = "before"
payload = """G.ARGS.LOC_COLOURS.sp_shuffyorange = G.C.SP_SHUFFYORANGE
"""
overwrite = true
match_indent = true