[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = """        RENTAL = HEX('b18f43'),"""
position = "after"
payload = """SP_SHUFFYORANGE = HEX("e67e22"),
SP_CATAROTPINK = HEX("E8A6BD"),
SP_EXOPLANETBLUE = HEX("0A53A8"),
SP_LENORMANDRED = HEX("B10202"),
SP_TRAMGREEN = HEX("78BE20"),
"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = """  return G.ARGS.LOC_COLOURS[_c] or _default or G.C.UI.TEXT_DARK"""
position = "before"
payload = """G.ARGS.LOC_COLOURS.sp_shuffyorange = G.C.SP_SHUFFYORANGE
G.ARGS.LOC_COLOURS.sp_catarotpink = G.C.SP_CATAROTPINK
G.ARGS.LOC_COLOURS.sp_exoplanetblue = G.C.SP_EXOPLANETBLUE
G.ARGS.LOC_COLOURS.sp_lenormandred = G.C.SP_LENORMANDRED
G.ARGS.LOC_COLOURS.sp_tramgreen = G.C.SP_TRAMGREEN
"""
overwrite = true
match_indent = true